Not Found: /
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: 'str' object is not callable
Not Found: /
Not Found: /
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: 'str' object is not callable
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: 'str' object is not callable
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: 'str' object is not callable
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 101, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 222, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 229, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 32, in wrapper
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 96, in get_callable
    mod = import_module(mod_name)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
ImportError: No module named views
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/teste/blog/views.py", line 30, in home
    return render_to_response('blog/index.html',locals(),context_instance=RequestContext(request),)
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 447, in render
    six.reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 433, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 509, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 429, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'home_index' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
Internal Server Error: /blog/cadastro-usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 101, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 222, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 229, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 32, in wrapper
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 96, in get_callable
    mod = import_module(mod_name)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/var/www/html/laboratorio/teste-planetkids/teste/blog/views.py", line 23, in <module>
    from django.shortcuts   import render_to_response,reverse
ImportError: cannot import name reverse
Internal Server Error: /blog/cadastro-usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/teste/blog/views.py", line 42, in usuario
    if form.is_valid():
UnboundLocalError: local variable 'form' referenced before assignment
Internal Server Error: /blog/cadastro-usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/teste/blog/views.py", line 43, in usuario
    novo_usuario = form.save()
  File "/var/www/html/laboratorio/teste-planetkids/teste/blog/forms.py", line 48, in save
    usuario = super(FormRegistro, self).save(commit=False)
NameError: global name 'FormRegistro' is not defined
Internal Server Error: /blog/cadastro-usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 101, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 222, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 229, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 32, in wrapper
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 96, in get_callable
    mod = import_module(mod_name)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/var/www/html/laboratorio/teste-planetkids/teste/blog/views.py", line 28, in <module>
    from forms      import FormUser
  File "/var/www/html/laboratorio/teste-planetkids/teste/blog/forms.py", line 25, in <module>
    class FormUser(forms.ModelForm):
  File "/var/www/html/laboratorio/teste-planetkids/teste/blog/forms.py", line 31, in FormUser
    first_name       = forms.CharField(unique=True,)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/fields.py", line 198, in __init__
    super(CharField, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'unique'
Internal Server Error: /blog/cadastro-usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/teste/blog/views.py", line 48, in usuario
    return render_to_response('blog/usuario.html',locals(),context_instance=RequestContext(request),)
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 127, in find_template
    source, display_name = loader(name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 149, in get_template_from_string
    return Template(source, origin, name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 153, in compile_string
    return parser.parse()
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 942, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 254, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 360, in compile_filter
    return FilterExpression(token, self)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 577, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: '"D/M/Y"' from 'user.date_joined|date"D/M/Y"'
Internal Server Error: /blog/cadastro-usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/teste/blog/views.py", line 48, in usuario
    return render_to_response('blog/usuario.html',locals(),context_instance=RequestContext(request),)
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 127, in find_template
    source, display_name = loader(name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 149, in get_template_from_string
    return Template(source, origin, name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 153, in compile_string
    return parser.parse()
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 942, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 254, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 360, in compile_filter
    return FilterExpression(token, self)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 577, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: ''D/M/Y'' from 'user.date_joined|date'D/M/Y''
Internal Server Error: /blog/cadastro-usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/teste/blog/views.py", line 45, in usuario
    usuario = User.objects.get(email=novo_usuario.cleaned_data['email'])
NameError: global name 'User' is not defined
Internal Server Error: /blog/cadastro-usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/teste/blog/views.py", line 46, in usuario
    usuario = User.objects.get(email=novo_usuario.cleaned_data['email'])
AttributeError: 'User' object has no attribute 'cleaned_data'
Not Found: /sair/
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/teste/blog/views.py", line 36, in home
    posts = Post.object.all()
AttributeError: type object 'Post' has no attribute 'object'
Not Found: /favicon.ico
Not Found: /favicon.ico
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 29, in card
    return render_to_response('card/index.html',locals(),context_instance=RequestContext(request),)
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 162, in render_to_string
    t = get_template(template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: card/index.html
Not Found: /favicon.ico
Not Found: /favicon.ico
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 40, in card
    return render_to_response('card/index.html',locals(),context_instance=RequestContext(request),)
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 91, in render
    output = force_text(output)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/encoding.py", line 100, in force_text
    s = s.__unicode__()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 103, in __str__
    return self.as_table()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 223, in as_table
    errors_on_separate_row = False)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 156, in _html_output
    if bf.is_hidden:
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 560, in is_hidden
    return self.field.widget.is_hidden
AttributeError: 'DateField' object has no attribute 'is_hidden'
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 34, in card
    if form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 121, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 273, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 282, in _clean_fields
    value = field.widget.value_from_datadict(self.data, self.files, self.add_prefix(name))
AttributeError: 'DateField' object has no attribute 'value_from_datadict'
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 34, in card
    if form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 121, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 273, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 282, in _clean_fields
    value = field.widget.value_from_datadict(self.data, self.files, self.add_prefix(name))
AttributeError: 'DateField' object has no attribute 'value_from_datadict'
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 101, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 222, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 229, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 32, in wrapper
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 96, in get_callable
    mod = import_module(mod_name)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 26, in <module>
    from forms import FormCard
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/forms.py", line 28, in <module>
    class FormCard(forms.ModelForm):
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/forms.py", line 37, in FormCard
    mes_val     = forms.IntegerField(widget=form.Select(choices=MESES_CHOICES),required=True,)
NameError: name 'form' is not defined
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 101, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 222, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 229, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 32, in wrapper
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 96, in get_callable
    mod = import_module(mod_name)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 26, in <module>
    from forms import FormCard
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/forms.py", line 28, in <module>
    class FormCard(forms.ModelForm):
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/forms.py", line 39, in FormCard
    cvc         = forms.IntegerField(label=u'Cód. de segurança',required=True,max_length=3)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/fields.py", line 226, in __init__
    super(IntegerField, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'max_length'
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/blog/views.py", line 51, in home
    return render_to_response('blog/index.html',locals(),context_instance=RequestContext(request),)
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 433, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 509, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 387, in _reverse_with_prefix
    possibilities = self.reverse_dict.getlist(lookup_view)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 296, in reverse_dict
    self._populate()
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 273, in _populate
    for name in pattern.reverse_dict:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 296, in reverse_dict
    self._populate()
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 285, in _populate
    lookups.appendlist(pattern.callback, (bits, p_pattern, pattern.default_args))
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 229, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 32, in wrapper
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 96, in get_callable
    mod = import_module(mod_name)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 26, in <module>
    from forms import FormCard
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/forms.py", line 28, in <module>
    class FormCard(forms.ModelForm):
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/forms.py", line 39, in FormCard
    cvc         = forms.IntegerField(label=u'Cód. de segurança',required=True,max_length=3)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/fields.py", line 226, in __init__
    super(IntegerField, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'max_length'
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 35, in card
    new_card = form.save()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 437, in save
    construct=False)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 94, in save_instance
    instance.save()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1511, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 898, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 450, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: card_card
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 34, in card
    if form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 121, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 274, in full_clean
    self._clean_form()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 300, in _clean_form
    self.cleaned_data = self.clean()
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/forms.py", line 53, in clean
    cvc=cleaned_data.get('cvc')
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/pycard/card.py", line 54, in __init__
    self.exp_date = ExpDate(month, year)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/pycard/card.py", line 155, in __init__
    weekday, day_count = monthrange(year, month)
  File "/usr/lib/python2.7/calendar.py", line 120, in monthrange
    raise IllegalMonthError(month)
IllegalMonthError: bad month number None; must be 1-12
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 34, in card
    if form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 121, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 274, in full_clean
    self._clean_form()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 300, in _clean_form
    self.cleaned_data = self.clean()
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/forms.py", line 53, in clean
    cvc=cleaned_data.get('cvc')
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/pycard/card.py", line 54, in __init__
    self.exp_date = ExpDate(month, year)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/pycard/card.py", line 155, in __init__
    weekday, day_count = monthrange(year, month)
  File "/usr/lib/python2.7/calendar.py", line 120, in monthrange
    raise IllegalMonthError(month)
IllegalMonthError: bad month number None; must be 1-12
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 34, in card
    if form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 121, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 274, in full_clean
    self._clean_form()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 300, in _clean_form
    self.cleaned_data = self.clean()
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/forms.py", line 53, in clean
    cvc=cleaned_data.get('cvc')
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/pycard/card.py", line 54, in __init__
    self.exp_date = ExpDate(month, year)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/pycard/card.py", line 155, in __init__
    weekday, day_count = monthrange(year, month)
  File "/usr/lib/python2.7/calendar.py", line 120, in monthrange
    raise IllegalMonthError(month)
IllegalMonthError: bad month number None; must be 1-12
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 34, in card
    if form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 121, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 274, in full_clean
    self._clean_form()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 300, in _clean_form
    self.cleaned_data = self.clean()
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/forms.py", line 53, in clean
    cvc=cleaned_data.get('cvc')
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/pycard/card.py", line 54, in __init__
    self.exp_date = ExpDate(month, year)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/pycard/card.py", line 155, in __init__
    weekday, day_count = monthrange(year, month)
  File "/usr/lib/python2.7/calendar.py", line 120, in monthrange
    raise IllegalMonthError(month)
IllegalMonthError: bad month number None; must be 1-12
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 34, in card
    if form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 121, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 274, in full_clean
    self._clean_form()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 300, in _clean_form
    self.cleaned_data = self.clean()
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/forms.py", line 53, in clean
    cvc=cleaned_data.get('cvc')
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/pycard/card.py", line 54, in __init__
    self.exp_date = ExpDate(month, year)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/pycard/card.py", line 155, in __init__
    weekday, day_count = monthrange(year, month)
  File "/usr/lib/python2.7/calendar.py", line 121, in monthrange
    day1 = weekday(year, month, 1)
  File "/usr/lib/python2.7/calendar.py", line 113, in weekday
    return datetime.date(year, month, day).weekday()
TypeError: an integer is required
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 34, in card
    if form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 121, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 274, in full_clean
    self._clean_form()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 300, in _clean_form
    self.cleaned_data = self.clean()
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/forms.py", line 57, in clean
    self.add_error('numero', 'Cartão invalido.')
AttributeError: 'FormCard' object has no attribute 'add_error'
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 34, in card
    if form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 121, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 274, in full_clean
    self._clean_form()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 300, in _clean_form
    self.cleaned_data = self.clean()
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/forms.py", line 53, in clean
    cvc=cleaned_data.get('cvc')
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/pycard/card.py", line 54, in __init__
    self.exp_date = ExpDate(month, year)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/pycard/card.py", line 155, in __init__
    weekday, day_count = monthrange(year, month)
  File "/usr/lib/python2.7/calendar.py", line 120, in monthrange
    raise IllegalMonthError(month)
IllegalMonthError: bad month number None; must be 1-12
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 34, in card
    if form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 121, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 274, in full_clean
    self._clean_form()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 300, in _clean_form
    self.cleaned_data = self.clean()
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/forms.py", line 53, in clean
    cvc=cleaned_data.get('cvc')
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/pycard/card.py", line 54, in __init__
    self.exp_date = ExpDate(month, year)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/pycard/card.py", line 155, in __init__
    weekday, day_count = monthrange(year, month)
  File "/usr/lib/python2.7/calendar.py", line 120, in monthrange
    raise IllegalMonthError(month)
IllegalMonthError: bad month number None; must be 1-12
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 34, in card
    if form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 121, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 274, in full_clean
    self._clean_form()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 300, in _clean_form
    self.cleaned_data = self.clean()
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/forms.py", line 53, in clean
    cvc=cleaned_data.get('cvc')
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/pycard/card.py", line 54, in __init__
    self.exp_date = ExpDate(month, year)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/pycard/card.py", line 155, in __init__
    weekday, day_count = monthrange(year, month)
  File "/usr/lib/python2.7/calendar.py", line 120, in monthrange
    raise IllegalMonthError(month)
IllegalMonthError: bad month number None; must be 1-12
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 34, in card
    if form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 121, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 274, in full_clean
    self._clean_form()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 300, in _clean_form
    self.cleaned_data = self.clean()
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/forms.py", line 48, in clean
    for form in self.forms:
AttributeError: 'FormCard' object has no attribute 'forms'
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 34, in card
    if form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 121, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 275, in full_clean
    self._post_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 387, in _post_clean
    self.instance = construct_instance(self, self.instance, opts.fields, opts.exclude)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 46, in construct_instance
    or not f.name in cleaned_data:
TypeError: argument of type 'NoneType' is not iterable
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 34, in card
    if form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 121, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 275, in full_clean
    self._post_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 387, in _post_clean
    self.instance = construct_instance(self, self.instance, opts.fields, opts.exclude)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 46, in construct_instance
    or not f.name in cleaned_data:
TypeError: argument of type 'NoneType' is not iterable
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 34, in card
    if form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 121, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 275, in full_clean
    self._post_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 387, in _post_clean
    self.instance = construct_instance(self, self.instance, opts.fields, opts.exclude)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 46, in construct_instance
    or not f.name in cleaned_data:
TypeError: argument of type 'NoneType' is not iterable
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 34, in card
    if form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 121, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 275, in full_clean
    self._post_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 387, in _post_clean
    self.instance = construct_instance(self, self.instance, opts.fields, opts.exclude)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 46, in construct_instance
    or not f.name in cleaned_data:
TypeError: argument of type 'NoneType' is not iterable
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 34, in card
    if form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 121, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 275, in full_clean
    self._post_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 387, in _post_clean
    self.instance = construct_instance(self, self.instance, opts.fields, opts.exclude)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 46, in construct_instance
    or not f.name in cleaned_data:
TypeError: argument of type 'NoneType' is not iterable
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 34, in card
    if form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 121, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 275, in full_clean
    self._post_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 404, in _post_clean
    validate_unique=False)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 935, in full_clean
    self.clean()
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/models.py", line 57, in clean
    cvc=self.cvc
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/pycard/card.py", line 53, in __init__
    self.number = self.non_digit_regexp.sub('', number)
TypeError: expected string or buffer
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 34, in card
    if form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 121, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 275, in full_clean
    self._post_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 404, in _post_clean
    validate_unique=False)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 935, in full_clean
    self.clean()
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/models.py", line 57, in clean
    cvc=self.cvc
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/pycard/card.py", line 54, in __init__
    self.exp_date = ExpDate(month, year)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/pycard/card.py", line 155, in __init__
    weekday, day_count = monthrange(year, month)
  File "/usr/lib/python2.7/calendar.py", line 120, in monthrange
    raise IllegalMonthError(month)
IllegalMonthError: bad month number None; must be 1-12
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 34, in card
    if form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 121, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 275, in full_clean
    self._post_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 404, in _post_clean
    validate_unique=False)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 935, in full_clean
    self.clean()
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/models.py", line 52, in clean
    ValidationError('Cartão invalido.')
NameError: global name 'ValidationError' is not defined
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 34, in card
    if form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 121, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 275, in full_clean
    self._post_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 404, in _post_clean
    validate_unique=False)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 935, in full_clean
    self.clean()
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/models.py", line 52, in clean
    print self.numero.value
AttributeError: 'NoneType' object has no attribute 'value'
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 34, in card
    if form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 121, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 273, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 291, in _clean_fields
    value = getattr(self, 'clean_%s' % name)()
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/forms.py", line 50, in clean_numero
    cvc=self.data['cvc']
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/pycard/card.py", line 54, in __init__
    self.exp_date = ExpDate(month, year)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/pycard/card.py", line 155, in __init__
    weekday, day_count = monthrange(year, month)
  File "/usr/lib/python2.7/calendar.py", line 120, in monthrange
    raise IllegalMonthError(month)
IllegalMonthError: bad month number u'1'; must be 1-12
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 40, in card
    return render_to_response('card/index.html',locals(),context_instance=RequestContext(request),)
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 91, in render
    output = force_text(output)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/encoding.py", line 100, in force_text
    s = s.__unicode__()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 425, in __str__
    return self.as_widget()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 465, in as_widget
    if auto_id and 'id' not in attrs and 'id' not in widget.attrs:
AttributeError: 'IntegerField' object has no attribute 'attrs'
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 40, in card
    return render_to_response('card/index.html',locals(),context_instance=RequestContext(request),)
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 91, in render
    output = force_text(output)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/encoding.py", line 100, in force_text
    s = s.__unicode__()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 425, in __str__
    return self.as_widget()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 465, in as_widget
    if auto_id and 'id' not in attrs and 'id' not in widget.attrs:
AttributeError: 'IntegerField' object has no attribute 'attrs'
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 40, in card
    return render_to_response('card/index.html',locals(),context_instance=RequestContext(request),)
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 91, in render
    output = force_text(output)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/encoding.py", line 100, in force_text
    s = s.__unicode__()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 425, in __str__
    return self.as_widget()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 465, in as_widget
    if auto_id and 'id' not in attrs and 'id' not in widget.attrs:
AttributeError: 'IntegerField' object has no attribute 'attrs'
Internal Server Error: /card-credit/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 101, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 222, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 229, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 32, in wrapper
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 96, in get_callable
    mod = import_module(mod_name)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/views.py", line 26, in <module>
    from forms import FormCard
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/forms.py", line 30, in <module>
    class FormCard(forms.ModelForm):
  File "/var/www/html/laboratorio/teste-planetkids/blog-teste/card/forms.py", line 41, in FormCard
    cvc         = forms.Field(label=u'Cód. de segurança',max_length=4,required=True)
TypeError: __init__() got an unexpected keyword argument 'max_length'
Internal Server Error: /blog/enviar-email/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aliss_000\projetos\blog-teste\blog\views.py", line 92, in enviar_email
    smtpserver.login('souzamelolarissa@gmail.com', '6b16ae55')
  File "C:\Python27\lib\smtplib.py", line 615, in login
    raise SMTPAuthenticationError(code, resp)
SMTPAuthenticationError: (534, '5.7.14 <https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbv4A\n5.7.14 JKNrN7wBjQvhJuczYizqdOHiUP6hXEvNud9XAh8ZDNMYUE8LvkP_1O70OmSMvGxSl7n7NJ\n5.7.14 oN7uHuWocn8lPLY4asEY-Cnnd64ZB-xUAfcFJnSEMj_uTP654KJSrsrs8q4MCwARleYmjf\n5.7.14 z9xQwHdQNRBoc9czckPDeNLwCn6cn7UvfoORpWAg52ny9xnPhHmQP9apRcO8AlzobO__sZ\n5.7.14 oHeVlkA> Please log in via your web browser and then try again.\n5.7.14 Learn more at\n5.7.14 https://support.google.com/mail/bin/answer.py?answer=78754 t2sm1089150qae.6 - gsmtp')
Internal Server Error: /blog/enviar-email/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aliss_000\projetos\blog-teste\blog\views.py", line 92, in enviar_email
    smtpserver.login('souzamelolarissa@gmail.com', '6b16ae55')
  File "C:\Python27\lib\smtplib.py", line 615, in login
    raise SMTPAuthenticationError(code, resp)
SMTPAuthenticationError: (534, '5.7.14 <https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbtwj\n5.7.14 wMk9mCwH4uaG8NYYwnlK2epFJbbp-CLrmcvMGy52EPJLok-GsyTzHovyALVE9p7p920bHa\n5.7.14 VzKjLStt0xaxJOMdPC3Q9_nb5M1JdwUwNiOhNH_AIulb-TIo6eR13NuFl-BgI0-Rwj9ZY5\n5.7.14 GCUbbYw3FIYOURXEK3-NkMnCljuigMfRHxhdrBPYKo8tFCBZlW9htGtdIdiUaFgYpUEBcX\n5.7.14 qplZDiheseVdSJyGpXVXhB2ZHINc> Please log in via your web browser and\n5.7.14 then try again.\n5.7.14 Learn more at\n5.7.14 https://support.google.com/mail/bin/answer.py?answer=78754 10sm1072464qap.39 - gsmtp')
Internal Server Error: /blog/enviar-email/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aliss_000\projetos\blog-teste\blog\views.py", line 92, in enviar_email
    smtpserver.login('souzamelolarissa@gmail.com', '6b16ae55')
  File "C:\Python27\lib\smtplib.py", line 615, in login
    raise SMTPAuthenticationError(code, resp)
SMTPAuthenticationError: (534, '5.7.14 <https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbvZF\n5.7.14 8Smp7AhMMv8CXT52qEyPnTRV9qQpsrhvmPIoBVpubtayrd3yI_y1AW9gfmljk7DS-N82-_\n5.7.14 huUieZnGx6JMP8TDzVpoLT9P2kksc10SbKEWMNz6uKqh1TbqacYqB9JS8FGhjNMGittJa0\n5.7.14 Yl_WlQc4v0Hj9a9KN11w59cucjJZK3q0FBab1RTXIYg6wuCyA2rCp0IiTfROS9lBWeiFZ9\n5.7.14 vuK0raw> Please log in via your web browser and then try again.\n5.7.14 Learn more at\n5.7.14 https://support.google.com/mail/bin/answer.py?answer=78754 d62sm1102674qga.15 - gsmtp')
Not Found: /favicon.ico
Internal Server Error: /admin/filebrowser/browse/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\filebrowser\decorators.py", line 39, in decorator
    raise ImproperlyConfigured(_("Error finding Upload-Folder (site.storage.location + site.directory). Maybe it does not exist?"))
ImproperlyConfigured: Error finding Upload-Folder (site.storage.location + site.directory). Maybe it does not exist?
Internal Server Error: /admin/filebrowser/browse/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\filebrowser\decorators.py", line 39, in decorator
    raise ImproperlyConfigured(_("Error finding Upload-Folder (site.storage.location + site.directory). Maybe it does not exist?"))
ImproperlyConfigured: Error finding Upload-Folder (site.storage.location + site.directory). Maybe it does not exist?
Internal Server Error: /admin/filebrowser/browse/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\filebrowser\decorators.py", line 39, in decorator
    raise ImproperlyConfigured(_("Error finding Upload-Folder (site.storage.location + site.directory). Maybe it does not exist?"))
ImproperlyConfigured: Error finding Upload-Folder (site.storage.location + site.directory). Maybe it does not exist?
Not Found: /favicon.ico
Internal Server Error: /admin/filebrowser/browse/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\filebrowser\decorators.py", line 39, in decorator
    raise ImproperlyConfigured(_("Error finding Upload-Folder (site.storage.location + site.directory). Maybe it does not exist?"))
ImproperlyConfigured: Error finding Upload-Folder (site.storage.location + site.directory). Maybe it does not exist?
Not Found: /admin/filebrowser/
Not Found: /grappelli
Not Found: /admin/grappelli/
Not Found: /admin/filebrowser/
Not Found: /filebrowser/
Internal Server Error: /admin/filebrowser/browse/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\filebrowser\decorators.py", line 39, in decorator
    raise ImproperlyConfigured(_("Error finding Upload-Folder (site.storage.location + site.directory). Maybe it does not exist?"))
ImproperlyConfigured: Error finding Upload-Folder (site.storage.location + site.directory). Maybe it does not exist?
Not Found: /filebrowser/
Not Found: /adminurl/filebrowser/
Not Found: /admin/filebrowser/
Not Found: /adminurl/filebrowser/
Not Found: /adminurl/filebrowser
Not Found: /blog
Not Found: /blog/
Not Found: /blog/
Not Found: /blog
Not Found: /admin/filebrowser/browse/
Not Found: /adminurl/filebrowser/createdir/
Not Found: /adminurl/jsi18n/
Not Found: /adminurl/jsi18n/
Not Found: /adminurl/jsi18n/
Not Found: /adminurl/jsi18n/
Not Found: /adminurl/jsi18n/
Not Found: /adminurl/jsi18n/
Not Found: /adminurl/jsi18n/
Not Found: /adminurl/jsi18n/
Not Found: /adminurl/jsi18n/
Not Found: /adminurl/
Not Found: /adminurl/jsi18n/
Not Found: /adminurl/
Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 139, in get_response
    response = response.render()
  File "C:\Python27\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Python27\lib\site-packages\django\template\response.py", line 82, in rendered_content
    content = template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1220, in render
    return self.nodelist.render(new_context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1196, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\templatetags\grp_dashboard_tags.py", line 58, in grp_render_dashboard_module
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 163, in init_with_context
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 224, in init_with_context
    items = self._visible_models(context['request'])
  File "C:\Python27\lib\site-packages\django\template\context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 139, in get_response
    response = response.render()
  File "C:\Python27\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Python27\lib\site-packages\django\template\response.py", line 82, in rendered_content
    content = template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1196, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\templatetags\grp_dashboard_tags.py", line 38, in grp_render_dashboard
    dashboard = get_index_dashboard(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\utils.py", line 45, in get_index_dashboard
    ), context)()
  File "C:\Python27\lib\site-packages\grappelli\dashboard\utils.py", line 31, in _get_dashboard_cls
    mod = import_module(mod)
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 40, in import_module
    __import__(name)
ImportError: No module named blog-teste.somefile
Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 139, in get_response
    response = response.render()
  File "C:\Python27\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Python27\lib\site-packages\django\template\response.py", line 82, in rendered_content
    content = template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1220, in render
    return self.nodelist.render(new_context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1196, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\templatetags\grp_dashboard_tags.py", line 58, in grp_render_dashboard_module
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 163, in init_with_context
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 224, in init_with_context
    items = self._visible_models(context['request'])
  File "C:\Python27\lib\site-packages\django\template\context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 139, in get_response
    response = response.render()
  File "C:\Python27\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Python27\lib\site-packages\django\template\response.py", line 82, in rendered_content
    content = template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1220, in render
    return self.nodelist.render(new_context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1196, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\templatetags\grp_dashboard_tags.py", line 58, in grp_render_dashboard_module
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 163, in init_with_context
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 224, in init_with_context
    items = self._visible_models(context['request'])
  File "C:\Python27\lib\site-packages\django\template\context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 139, in get_response
    response = response.render()
  File "C:\Python27\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Python27\lib\site-packages\django\template\response.py", line 82, in rendered_content
    content = template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1220, in render
    return self.nodelist.render(new_context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1196, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\templatetags\grp_dashboard_tags.py", line 58, in grp_render_dashboard_module
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 163, in init_with_context
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 224, in init_with_context
    items = self._visible_models(context['request'])
  File "C:\Python27\lib\site-packages\django\template\context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 139, in get_response
    response = response.render()
  File "C:\Python27\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Python27\lib\site-packages\django\template\response.py", line 82, in rendered_content
    content = template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1220, in render
    return self.nodelist.render(new_context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1196, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\templatetags\grp_dashboard_tags.py", line 58, in grp_render_dashboard_module
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 163, in init_with_context
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 224, in init_with_context
    items = self._visible_models(context['request'])
  File "C:\Python27\lib\site-packages\django\template\context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 139, in get_response
    response = response.render()
  File "C:\Python27\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Python27\lib\site-packages\django\template\response.py", line 82, in rendered_content
    content = template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1220, in render
    return self.nodelist.render(new_context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1196, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\templatetags\grp_dashboard_tags.py", line 58, in grp_render_dashboard_module
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 306, in init_with_context
    request = context['request']
  File "C:\Python27\lib\site-packages\django\template\context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 139, in get_response
    response = response.render()
  File "C:\Python27\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Python27\lib\site-packages\django\template\response.py", line 82, in rendered_content
    content = template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1220, in render
    return self.nodelist.render(new_context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1196, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\templatetags\grp_dashboard_tags.py", line 58, in grp_render_dashboard_module
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 163, in init_with_context
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 224, in init_with_context
    items = self._visible_models(context['request'])
  File "C:\Python27\lib\site-packages\django\template\context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 139, in get_response
    response = response.render()
  File "C:\Python27\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Python27\lib\site-packages\django\template\response.py", line 82, in rendered_content
    content = template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1220, in render
    return self.nodelist.render(new_context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1196, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\templatetags\grp_dashboard_tags.py", line 58, in grp_render_dashboard_module
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 163, in init_with_context
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 224, in init_with_context
    items = self._visible_models(context['request'])
  File "C:\Python27\lib\site-packages\django\template\context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 139, in get_response
    response = response.render()
  File "C:\Python27\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Python27\lib\site-packages\django\template\response.py", line 82, in rendered_content
    content = template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1220, in render
    return self.nodelist.render(new_context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1196, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\templatetags\grp_dashboard_tags.py", line 58, in grp_render_dashboard_module
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 163, in init_with_context
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 224, in init_with_context
    items = self._visible_models(context['request'])
  File "C:\Python27\lib\site-packages\django\template\context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 139, in get_response
    response = response.render()
  File "C:\Python27\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Python27\lib\site-packages\django\template\response.py", line 82, in rendered_content
    content = template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1220, in render
    return self.nodelist.render(new_context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1196, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\templatetags\grp_dashboard_tags.py", line 58, in grp_render_dashboard_module
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 163, in init_with_context
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 224, in init_with_context
    items = self._visible_models(context['request'])
  File "C:\Python27\lib\site-packages\django\template\context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 139, in get_response
    response = response.render()
  File "C:\Python27\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Python27\lib\site-packages\django\template\response.py", line 82, in rendered_content
    content = template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1220, in render
    return self.nodelist.render(new_context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1196, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\templatetags\grp_dashboard_tags.py", line 58, in grp_render_dashboard_module
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 163, in init_with_context
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 224, in init_with_context
    items = self._visible_models(context['request'])
  File "C:\Python27\lib\site-packages\django\template\context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 139, in get_response
    response = response.render()
  File "C:\Python27\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Python27\lib\site-packages\django\template\response.py", line 82, in rendered_content
    content = template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1220, in render
    return self.nodelist.render(new_context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1196, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\templatetags\grp_dashboard_tags.py", line 58, in grp_render_dashboard_module
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 163, in init_with_context
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 224, in init_with_context
    items = self._visible_models(context['request'])
  File "C:\Python27\lib\site-packages\django\template\context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 139, in get_response
    response = response.render()
  File "C:\Python27\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Python27\lib\site-packages\django\template\response.py", line 82, in rendered_content
    content = template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1220, in render
    return self.nodelist.render(new_context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1196, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\templatetags\grp_dashboard_tags.py", line 58, in grp_render_dashboard_module
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 224, in init_with_context
    items = self._visible_models(context['request'])
  File "C:\Python27\lib\site-packages\django\template\context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 139, in get_response
    response = response.render()
  File "C:\Python27\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Python27\lib\site-packages\django\template\response.py", line 82, in rendered_content
    content = template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1220, in render
    return self.nodelist.render(new_context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1196, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\templatetags\grp_dashboard_tags.py", line 58, in grp_render_dashboard_module
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 224, in init_with_context
    items = self._visible_models(context['request'])
  File "C:\Python27\lib\site-packages\django\template\context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 139, in get_response
    response = response.render()
  File "C:\Python27\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Python27\lib\site-packages\django\template\response.py", line 82, in rendered_content
    content = template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1220, in render
    return self.nodelist.render(new_context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1196, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\templatetags\grp_dashboard_tags.py", line 58, in grp_render_dashboard_module
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 224, in init_with_context
    items = self._visible_models(context['request'])
  File "C:\Python27\lib\site-packages\django\template\context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 139, in get_response
    response = response.render()
  File "C:\Python27\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Python27\lib\site-packages\django\template\response.py", line 82, in rendered_content
    content = template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1220, in render
    return self.nodelist.render(new_context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1196, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\templatetags\grp_dashboard_tags.py", line 58, in grp_render_dashboard_module
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 224, in init_with_context
    items = self._visible_models(context['request'])
  File "C:\Python27\lib\site-packages\django\template\context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 139, in get_response
    response = response.render()
  File "C:\Python27\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Python27\lib\site-packages\django\template\response.py", line 82, in rendered_content
    content = template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1220, in render
    return self.nodelist.render(new_context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 1196, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\templatetags\grp_dashboard_tags.py", line 58, in grp_render_dashboard_module
    module.init_with_context(context)
  File "C:\Python27\lib\site-packages\grappelli\dashboard\modules.py", line 224, in init_with_context
    items = self._visible_models(context['request'])
  File "C:\Python27\lib\site-packages\django\template\context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Not Found: /adminurl/jsi18n/
Not Found: /adminurl/
Not Found: /adminurl/
Internal Server Error: /admin/filebrowser/upload/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\filebrowser\decorators.py", line 45, in decorator
    return function(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\admin\views\decorators.py", line 17, in _checklogin
    return view_func(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\filebrowser\sites.py", line 405, in upload
    }, context_instance=Context(request, current_app=self.name))
  File "C:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 88, in render
    output = self.filter_expression.resolve(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 585, in resolve
    obj = self.var.resolve(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 735, in resolve
    value = self._resolve_lookup(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 789, in _resolve_lookup
    current = current()
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 72, in super
    return mark_safe(self.render(self.context))
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 433, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 480, in reverse
    app_list = resolver.app_dict[ns]
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 310, in app_dict
    self._populate()
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 273, in _populate
    for name in pattern.reverse_dict:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 296, in reverse_dict
    self._populate()
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 285, in _populate
    lookups.appendlist(pattern.callback, (bits, p_pattern, pattern.default_args))
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 229, in callback
    self._callback = get_callable(self._callback_str)
  File "C:\Python27\lib\site-packages\django\utils\functional.py", line 32, in wrapper
    result = func(*args)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 117, in get_callable
    (lookup_view, mod_name))
ViewDoesNotExist: Could not import galeria.views.galeria_index. View does not exist in module galeria.views.
Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 101, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 40, in import_module
    __import__(name)
  File "C:\Users\aliss_000\projetos\blog-teste\teste\urls.py", line 40, in <module>
    url(r'^admin/', include(admin.site.urls)),
  File "C:\Python27\lib\site-packages\django\contrib\admin\sites.py", line 253, in urls
    return self.get_urls(), self.app_name, self.name
  File "C:\Python27\lib\site-packages\django\contrib\admin\sites.py", line 247, in get_urls
    include(model_admin.urls))
AttributeError: 'ArquivoInline' object has no attribute 'urls'
Internal Server Error: /admin/galeria/galeria/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\admin\options.py", line 430, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\utils\decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\admin\sites.py", line 198, in inner
    return view(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\utils\decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\utils\decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\utils\decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "C:\Python27\lib\site-packages\django\contrib\admin\options.py", line 1304, in changelist_view
    self)
  File "C:\Python27\lib\site-packages\django\contrib\admin\views\main.py", line 106, in __init__
    self.get_results(request)
  File "C:\Python27\lib\site-packages\django\contrib\admin\views\main.py", line 220, in get_results
    result_count = paginator.count
  File "C:\Python27\lib\site-packages\django\core\paginator.py", line 72, in _get_count
    self._count = self.object_list.count()
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 291, in count
    return self.query.get_count(using=self.db)
  File "C:\Python27\lib\site-packages\django\db\models\sql\query.py", line 390, in get_count
    number = obj.get_aggregation(using=using)[None]
  File "C:\Python27\lib\site-packages\django\db\models\sql\query.py", line 356, in get_aggregation
    result = query.get_compiler(using).execute_sql(SINGLE)
  File "C:\Python27\lib\site-packages\django\db\models\sql\compiler.py", line 781, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Python27\lib\site-packages\django\db\backends\util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\sqlite3\base.py", line 450, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: galeria_galeria
Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 101, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 40, in import_module
    __import__(name)
  File "C:\Users\aliss_000\projetos\blog-teste\teste\urls.py", line 40, in <module>
    url(r'^admin/', include(admin.site.urls)),
  File "C:\Python27\lib\site-packages\django\contrib\admin\sites.py", line 253, in urls
    return self.get_urls(), self.app_name, self.name
  File "C:\Python27\lib\site-packages\django\contrib\admin\sites.py", line 247, in get_urls
    include(model_admin.urls))
AttributeError: 'ArquivoInline' object has no attribute 'urls'
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aliss_000\projetos\blog-teste\blog\views.py", line 52, in home
    return render_to_response('blog/index.html',locals(),context_instance=RequestContext(request),)
  File "C:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 127, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 149, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 153, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 1306, in url
    viewname = parser.compile_filter(bits[1])
  File "C:\Python27\lib\site-packages\django\template\base.py", line 360, in compile_filter
    return FilterExpression(token, self)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 577, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: ''galeria' from ''galeria'. The syntax of 'url' changed in Django 1.5, see the docs.
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aliss_000\projetos\blog-teste\blog\views.py", line 52, in home
    return render_to_response('blog/index.html',locals(),context_instance=RequestContext(request),)
  File "C:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 127, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 149, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 153, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 1306, in url
    viewname = parser.compile_filter(bits[1])
  File "C:\Python27\lib\site-packages\django\template\base.py", line 360, in compile_filter
    return FilterExpression(token, self)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 577, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: ''galeria' from ''galeria'. The syntax of 'url' changed in Django 1.5, see the docs.
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aliss_000\projetos\blog-teste\blog\views.py", line 52, in home
    return render_to_response('blog/index.html',locals(),context_instance=RequestContext(request),)
  File "C:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 127, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 149, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 153, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 1306, in url
    viewname = parser.compile_filter(bits[1])
  File "C:\Python27\lib\site-packages\django\template\base.py", line 360, in compile_filter
    return FilterExpression(token, self)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 577, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: ''galeria_index' from ''galeria_index'. The syntax of 'url' changed in Django 1.5, see the docs.
Not Found: /galeria/path/to/your/img-th
Not Found: /galeria/path/to/your/img
Not Found: /galeria/path/to/your/img
Not Found: /galeria/path/to/your/img
Not Found: /galeria/path/to/your/img-th
Not Found: /galeria/path/to/your/img-th
Not Found: /galeria/path/to/your/img-th
Not Found: /galeria/path/to/your/img-th
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /adminurl/filebrowser/detail/
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Internal Server Error: /adminurl/filebrowser/detail/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 101, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 40, in import_module
    __import__(name)
  File "C:\Users\aliss_000\projetos\blog-teste\teste\urls.py", line 27, in <module>
    admin.autodiscover()
  File "C:\Python27\lib\site-packages\django\contrib\admin\__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 40, in import_module
    __import__(name)
  File "C:\Users\aliss_000\projetos\blog-teste\blog\admin.py", line 45, in <module>
    from teste.actions import foo
  File "C:\Users\aliss_000\projetos\blog-teste\teste\actions.py", line 33, in <module>
    foo.applies_to(lambda fileobject: fileobject.filetype == 'Image')
AttributeError: 'function' object has no attribute 'applies_to'
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Internal Server Error: /admin/filebrowser/detail/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\filebrowser\decorators.py", line 65, in decorator
    return function(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\filebrowser\decorators.py", line 45, in decorator
    return function(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\admin\views\decorators.py", line 17, in _checklogin
    return view_func(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\filebrowser\sites.py", line 487, in detail
    self.storage.move(fileobject.path, os.path.join(fileobject.head, new_name))
  File "C:\Python27\lib\site-packages\filebrowser\storage.py", line 58, in move
    file_move_safe(self.path(old_file_name), self.path(new_file_name), allow_overwrite=True)
  File "C:\Python27\lib\site-packages\django\core\files\move.py", line 66, in file_move_safe
    with open(old_file_name, 'rb') as old_file:
IOError: [Errno 13] Permission denied: u'C:\\Users\\aliss_000\\projetos\\blog-teste\\teste\\media\\uploads\\teste'
Internal Server Error: /admin/filebrowser/detail/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\filebrowser\decorators.py", line 65, in decorator
    return function(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\filebrowser\decorators.py", line 45, in decorator
    return function(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\admin\views\decorators.py", line 17, in _checklogin
    return view_func(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\filebrowser\sites.py", line 487, in detail
    self.storage.move(fileobject.path, os.path.join(fileobject.head, new_name))
  File "C:\Python27\lib\site-packages\filebrowser\storage.py", line 58, in move
    file_move_safe(self.path(old_file_name), self.path(new_file_name), allow_overwrite=True)
  File "C:\Python27\lib\site-packages\django\core\files\move.py", line 66, in file_move_safe
    with open(old_file_name, 'rb') as old_file:
IOError: [Errno 13] Permission denied: u'C:\\Users\\aliss_000\\projetos\\blog-teste\\teste\\media\\uploads\\teste'
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Internal Server Error: /admin/filebrowser/detail/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 101, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 40, in import_module
    __import__(name)
  File "C:\Users\aliss_000\projetos\blog-teste\teste\urls.py", line 64, in <module>
    from teste.actions import foo
  File "C:\Users\aliss_000\projetos\blog-teste\teste\actions.py", line 35, in <module>
    foo.applies_to(lambda fileobject: fileobject.filetype == 'Video')
AttributeError: 'function' object has no attribute 'applies_to'
Internal Server Error: /admin/filebrowser/browse/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 101, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 40, in import_module
    __import__(name)
  File "C:\Users\aliss_000\projetos\blog-teste\teste\urls.py", line 64, in <module>
    from teste.actions import foo
  File "C:\Users\aliss_000\projetos\blog-teste\teste\actions.py", line 35, in <module>
    foo.applies_to(lambda fileobject: fileobject.filetype == 'Video')
AttributeError: 'function' object has no attribute 'applies_to'
Internal Server Error: /admin/filebrowser/detail/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\filebrowser\decorators.py", line 65, in decorator
    return function(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\filebrowser\decorators.py", line 45, in decorator
    return function(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\admin\views\decorators.py", line 17, in _checklogin
    return view_func(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\filebrowser\sites.py", line 481, in detail
    action_response = action(request=request, fileobjects=[fileobject])
  File "C:\Users\aliss_000\projetos\blog-teste\teste\actions.py", line 36, in make_monochrome
    transpose_image(request, fileobjects, 'L')
  File "C:\Python27\lib\site-packages\filebrowser\actions.py", line 36, in transpose_image
    new_image = im.transpose(operation)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 1915, in transpose
    return self._new(self.im.transpose(method))
TypeError: an integer is required
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Internal Server Error: /admin/filebrowser/detail/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\filebrowser\decorators.py", line 65, in decorator
    return function(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\filebrowser\decorators.py", line 45, in decorator
    return function(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\admin\views\decorators.py", line 17, in _checklogin
    return view_func(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\filebrowser\sites.py", line 481, in detail
    action_response = action(request=request, fileobjects=[fileobject])
  File "C:\Users\aliss_000\projetos\blog-teste\teste\actions.py", line 95, in make_monochrome
    convert_image(request, fileobjects, 'L')
  File "C:\Users\aliss_000\projetos\blog-teste\teste\actions.py", line 87, in convert_image
    files = '&f='.join([f.path_relative for f in fileobjects])
AttributeError: FileObject instance has no attribute 'path_relative'
Internal Server Error: /admin/filebrowser/detail/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\filebrowser\decorators.py", line 65, in decorator
    return function(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\filebrowser\decorators.py", line 45, in decorator
    return function(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\admin\views\decorators.py", line 17, in _checklogin
    return view_func(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\filebrowser\sites.py", line 481, in detail
    action_response = action(request=request, fileobjects=[fileobject])
  File "C:\Users\aliss_000\projetos\blog-teste\teste\actions.py", line 96, in make_monochrome
    convert_image(request, fileobjects, 'L')
  File "C:\Users\aliss_000\projetos\blog-teste\teste\actions.py", line 65, in convert_image
    files = '&f='.join([f.path_relative for f in fileobjects])
AttributeError: FileObject instance has no attribute 'path_relative'
Internal Server Error: /admin/filebrowser/browse/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\filebrowser\decorators.py", line 45, in decorator
    return function(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\admin\views\decorators.py", line 17, in _checklogin
    return view_func(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\filebrowser\sites.py", line 356, in browse
    }, context_instance=Context(request, current_app=self.name))
  File "C:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return self.render_template(self.template, context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 137, in render_template
    output = template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\filebrowser\templatetags\fb_versions.py", line 98, in render
    raise e
IOError: cannot identify image file <File: C:\Users\aliss_000\projetos\blog-teste\teste\media\uploads\rock_lee_sd\ep01\naruto_sd_-_hinata_sets_off_some_fireworks.mp4>
Internal Server Error: /admin/filebrowser/browse/
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\filebrowser\decorators.py", line 45, in decorator
    return function(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\admin\views\decorators.py", line 17, in _checklogin
    return view_func(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\filebrowser\sites.py", line 356, in browse
    }, context_instance=Context(request, current_app=self.name))
  File "C:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 155, in render
    return self.render_template(self.template, context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 137, in render_template
    output = template.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\filebrowser\templatetags\fb_versions.py", line 98, in render
    raise e
IOError: cannot identify image file <File: C:\Users\aliss_000\projetos\blog-teste\teste\media\uploads\rock_lee_sd\ep01\naruto_sd_-_hinata_sets_off_some_fireworks.mp4>
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
