Traceback (most recent call last):
  File "/home/planetkids/laboratorio/blog-teste/log/views.py", line 40, in debug
    raise ObjectDoesNotExist
ObjectDoesNotExist

2015-05-25 15:34:47,814 [ERROR] log.views: Traceback (most recent call last):
  File "/home/planetkids/laboratorio/blog-teste/log/views.py", line 40, in debug
    raise ObjectDoesNotExist
ObjectDoesNotExist

2015-05-25 15:35:58,484 [ERROR] log.views: Traceback (most recent call last):
  File "/home/planetkids/laboratorio/blog-teste/log/views.py", line 40, in debug
    raise ObjectDoesNotExist
ObjectDoesNotExist

2015-05-25 15:37:09,452 [ERROR] log.views: Traceback (most recent call last):
  File "/home/planetkids/laboratorio/blog-teste/log/views.py", line 40, in debug
    raise ObjectDoesNotExist
ObjectDoesNotExist

2015-05-25 15:37:18,251 [ERROR] log.views: Traceback (most recent call last):
  File "/home/planetkids/laboratorio/blog-teste/log/views.py", line 40, in debug
    raise ObjectDoesNotExist
ObjectDoesNotExist

2015-05-25 15:37:56,094 [ERROR] django.request: Internal Server Error: /log/debug/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/planetkids/laboratorio/blog-teste/log/views.py", line 39, in debug
    raise ObjectDoesNotExist
ObjectDoesNotExist
2015-05-25 15:38:51,680 [ERROR] django.request: Internal Server Error: /log/debug/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/planetkids/laboratorio/blog-teste/log/views.py", line 29, in debug
    raise ObjectDoesNotExist
ObjectDoesNotExist
2015-05-25 15:39:31,765 [ERROR] django.request: Internal Server Error: /log/debug/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/planetkids/laboratorio/blog-teste/log/views.py", line 29, in debug
    raise ObjectDoesNotExist
ObjectDoesNotExist
2015-05-25 15:40:24,776 [ERROR] django.request: Internal Server Error: /log/debug/ 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/planetkids/laboratorio/blog-teste/log/views.py", line 29, in debug
    raise ObjectDoesNotExist
ObjectDoesNotExist
2015-05-25 15:40:34,238 [ERROR] django.request: Internal Server Error: /log/debug/ 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/planetkids/laboratorio/blog-teste/log/views.py", line 29, in debug
    raise ObjectDoesNotExist
ObjectDoesNotExist

 2015-05-25 15:41:00,141 [ERROR] django.request: Internal Server Error: /log/debug/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/planetkids/laboratorio/blog-teste/log/views.py", line 29, in debug
    raise ObjectDoesNotExist
ObjectDoesNotExist

 2015-05-25 15:41:29,197 [ERROR] django.request: Internal Server Error: /log/debug/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/planetkids/laboratorio/blog-teste/log/views.py", line 29, in debug
    raise ObjectDoesNotExist
ObjectDoesNotExist

 2015-05-25 15:41:36,714 [ERROR] django.request: Internal Server Error: /log/debug/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/planetkids/laboratorio/blog-teste/log/views.py", line 29, in debug
    raise ObjectDoesNotExist
ObjectDoesNotExist

2015-05-25 15:42:47,005 [ERROR] django.request: Internal Server Error: /log/debug/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/planetkids/laboratorio/blog-teste/log/views.py", line 29, in debug
    raise ObjectDoesNotExist
ObjectDoesNotExist

2015-05-25 15:44:29,353 [WARNING] django.request: Not Found: /log/debug/

2015-05-25 15:46:59,215 [WARNING] django.request: Not Found: /log/debug/
